version: '3.7'

networks:
  payment_system:
    name: payment_system
    driver: bridge


services:
  tomcat:
    container_name: user-system-tomcat
    image: tomcat:8.5.99
    ports:
      - "8082:8080"
    volumes:
      - ./target/UserService-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/UserService.war
    networks:
      - payment_system
    depends_on:
      - postgres

  postgres:
    container_name: user-system-postgres
    image: postgres
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - payment_system